version: 2

models:
  - name: stg_customer
    description: "Staging: raw customer data"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_product
    description: "Staging: raw product data"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_region
    description: "Staging: raw region data"
    columns:
      - name: region_id
        tests:
          - unique
          - not_null

  - name: stg_sales
    description: "Staging: raw sales fact"
    columns:
      - name: sale_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customer')
              field: customer_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_product')
              field: product_id
      - name: sale_date
        tests:
          - not_null