version: 2

models:
  - name: dim_department
    description: "Final: department dimension"
    columns:
      - name: department_id
        tests:
          - unique
          - not_null

  - name: dim_customer
    description: "Final: customer dimension"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: dim_product
    description: "Final: product dimension"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_region
    description: "Final: region dimension"
    columns:
      - name: region_id
        tests:
          - unique
          - not_null

  - name: fct_sales
    description: "Final: sales fact table (incremental)"
